apiVersion: v1
kind: ConfigMap
metadata:
  name: normalization-red-alerts
  namespace: observability
# RED alerting rules for the normalization service in the data processing pipeline.
data:
  normalization-red.yaml: |
    groups:
    - name: normalization-red
      rules:
      - alert: ALERT_NORMALIZATION_ERROR_RATIO
        expr: normalization:error_ratio:ratio5m > 0.03
        for: 5m
        labels:
          severity: warning
          service: normalization
          alert_type: error_rate
        annotations:
          summary: "Normalization error ratio above threshold"
          description: "Normalization error ratio is {{ $value | humanizePercentage }} (threshold 3%)"
          runbook_url: "https://docs.254carbon.local/runbooks/normalization-error-ratio"

      - alert: ALERT_NORMALIZATION_PROCESSING_LATENCY
        expr: normalization:processing_duration_seconds:p95 > 2.0
        for: 5m
        labels:
          severity: warning
          service: normalization
          alert_type: latency
        annotations:
          summary: "Normalization processing latency elevated"
          description: "Normalization P95 processing latency is {{ $value }}s (threshold 2s)"
          runbook_url: "https://docs.254carbon.local/runbooks/normalization-latency"

      - alert: ALERT_NORMALIZATION_DLQ_SPIKE
        expr: normalization:dlq_messages:rate5m > 5
        for: 3m
        labels:
          severity: critical
          service: normalization
          alert_type: dlq_rate
        annotations:
          summary: "Normalization DLQ ingestion spike"
          description: "DLQ/failed records are {{ $value }} msg/s over the last 5 minutes"
          runbook_url: "https://docs.254carbon.local/runbooks/normalization-dlq"

      - alert: ALERT_NORMALIZATION_SERVICE_DOWN
        expr: up{job="normalization"} == 0
        for: 1m
        labels:
          severity: critical
          service: normalization
          alert_type: availability
        annotations:
          summary: "Normalization service unreachable"
          description: "Prometheus reports normalization target down for 1m"
          runbook_url: "https://docs.254carbon.local/runbooks/normalization-service-down"
