apiVersion: v1
kind: Namespace
metadata:
  name: k6-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k6-operator
  namespace: k6-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k6-operator
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["k6.io"]
  resources:
  - k6s
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k6-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k6-operator
subjects:
- kind: ServiceAccount
  name: k6-operator
  namespace: k6-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-operator
  namespace: k6-system
  labels:
    app: k6-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-operator
  template:
    metadata:
      labels:
        app: k6-operator
    spec:
      serviceAccountName: k6-operator
      containers:
        - name: k6-operator
          image: grafana/k6-operator:latest
          ports:
            - containerPort: 8080
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k6-operator"
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
