apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Aggregates base scaffolding and component manifests into a runnable
# observability stack. Use `patchesStrategicMerge`/`patchesJson6902` to apply
# environment-specific overrides (e.g., local vs. production).

# Base resources
resources:
  - base/

# Prometheus stack
  - prometheus/prometheus.yaml
  - prometheus/prometheus-deployment.yaml
  - prometheus/rules/general-rules.yaml
  - prometheus/rules/slo-burn-rules.yaml
  - prometheus/alertmanager.yaml
  - prometheus/alertmanager-deployment.yaml

# OpenTelemetry Collector
  - otel-collector/collector-config.yaml
  - otel-collector/collector-deployment.yaml

# Grafana
  - grafana/grafana-config.yaml
  - grafana/grafana-deployment.yaml
  - grafana/datasources/prometheus.yaml
  - grafana/dashboards-provisioning/dashboards.yaml

# Tempo (tracing)
  - tempo/tempo-config.yaml
  - tempo/tempo-deployment.yaml

# Loki (logging) - Phase 2
  - loki/loki-config.yaml
  - loki/loki-deployment.yaml

# Alert rules
  - ../alerts/RED/gateway_red.yaml
  - ../alerts/RED/streaming_red.yaml
  - ../alerts/SLO/api_latency_slo.yaml

# Common labels
commonLabels:
  app.kubernetes.io/name: 254carbon-observability
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/component: observability
  app.kubernetes.io/part-of: 254carbon-platform

# Namespace
namespace: observability

# Images
images:
  - name: prom/prometheus
    newTag: v2.45.0
  - name: prom/alertmanager
    newTag: v0.25.0
  - name: grafana/grafana
    newTag: 10.2.0
  - name: otel/opentelemetry-collector-contrib
    newTag: 0.85.0
  - name: grafana/tempo
    newTag: 2.3.1
  - name: grafana/loki
    newTag: 2.9.0
  - name: grafana/promtail
    newTag: 2.9.0
  - name: minio/minio
    newTag: latest

# ConfigMap generator for dashboards
configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/access/gateway_overview.json
    options:
      labels:
        app.kubernetes.io/name: grafana-dashboards
        app.kubernetes.io/component: dashboards

# Secret generator for sensitive data
secretGenerator:
  - name: grafana-admin
    literals:
      - admin-user=admin
      - admin-password=admin
    options:
      labels:
        app.kubernetes.io/name: grafana-admin
        app.kubernetes.io/component: auth

# Patches for environment-specific configurations
patchesStrategicMerge:
  - patches/local-patch.yaml
  - patches/staging-patch.yaml
  - patches/production-patch.yaml

# Patches for resource limits
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: prometheus
    path: patches/prometheus-resources.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana
    path: patches/grafana-resources.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: otel-collector
    path: patches/otel-collector-resources.yaml

# Replicas configuration
replicas:
  - name: prometheus
    count: 1
  - name: grafana
    count: 1
  - name: otel-collector
    count: 1
  - name: tempo
    count: 1
  - name: loki
    count: 1
  - name: promtail
    count: 1
  - name: minio
    count: 1
