# ServiceAccounts used by the observability deployments. Keep a 1:1 mapping
# with each component for clearer security boundaries and RBAC bindings.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo
  namespace: observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: observability
