apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gotk-sync
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gotk-sync
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gotk-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gotk-sync
subjects:
- kind: ServiceAccount
  name: gotk-sync
  namespace: flux-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotk-sync
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotk-sync
  template:
    metadata:
      labels:
        app: gotk-sync
    spec:
      serviceAccountName: gotk-sync
      containers:
      - name: manager
        image: fluxcd/flux-cli:v2.0.1
        command:
        - /bin/sh
        - -c
        - |
          flux install --components=source-controller,kustomize-controller,helm-controller,notification-controller
          kubectl wait --for=condition=available --timeout=300s deployment/kustomize-controller -n flux-system
          kubectl wait --for=condition=available --timeout=300s deployment/source-controller -n flux-system
          kubectl wait --for=condition=available --timeout=300s deployment/helm-controller -n flux-system
          kubectl wait --for=condition=available --timeout=300s deployment/notification-controller -n flux-system
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
